---
# Choose endpoint type (this will override the value of clouds.yaml)
endpoint_type: internal
cloud: default

image:
  repository: quay.io/niedbalski/openstack-exporter-linux-amd64
  tag: v1.2.0
  pullPolicy: Always

serviceMonitor:
  interval: 1m
  scrapeTimeout: 30s

# Add extra args to the exporter.
# Doc: https://github.com/openstack-exporter/openstack-exporter#command-line-options
#extraArgs:
#  - --disable-service.baremetal
#  - --disable-service.container-infra
#  - --disable-service.object-store

# Add extra labels
#commonLabels:
#  prometheus.io/monitor: "true"

# Add extra volumes mounted to openstack-exporter deployment
# Useful for mounting CA Certificates
#extraVolumes:
#- name: company-ca
#  configMap:
#    name: my-company-ca
#    items:
#    - key: ca
#      path: my-company-ca
#
#extraVolumeMounts:
#- mountPath: /etc/ssl/certs/my-company-ca
#  name: company-ca
#  subPath: my-company-ca

# Generate a secret for clouds.yaml
# Doc: https://github.com/openstack-exporter/openstack-exporter#openstack-configuration
clouds_yaml_config: |
  clouds.yaml: |
      clouds:
        default:
          region_name: your-region-here
          auth:
            username: your-user-here
            password: your-password-here
            project_name: your-project-here
            project_domain_name: 'Default'
            user_domain_name: 'Default'
            auth_url: 'http://your-url-here:5000/v3'
